# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cpp_calculate_skewness_kurtosis <- function(data) {
    .Call('_pearson_diagram_cpp_calculate_skewness_kurtosis', PACKAGE = 'pearson.diagram', data)
}

